import { type Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'

import HaikuCard from './_components/haiku_card'

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
          <div className="nav-bar">
            <button type="button">
              <Link href="/" className='nav-bar-link'>
                <Image
                  src="/nav-bar/home.svg"
                  alt="Home"
                  width={32}
                  height={32}
                />
              </Link>
            </button>
            <button type="button" className="post-icon">
              <Link href="/compose" className='nav-bar-link'>
                <Image
                  src="/nav-bar/post.svg"
                  alt="Post"
                  width={32}
                  height={32}
                />
              </Link>
            </button>
            <button type="button">
              <Link href="/profile" className='nav-bar-link'>
                <Image
                  src="/nav-bar/profile.svg"
                  alt="Profile"
                  width={32}
                  height={32}
                />
              </Link>
            </button>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}